nim.py (built in repl.it) See link to nim.py project...   https://replit.com/join/bmiplqsica-jmtheo8
gol.py (built in colab)  See link to gol.py project...    https://colab.research.google.com/drive/16irSytmJEVkblRRNfPigPU03eSt7QpCq?usp=sharing
binsearch.py (built in     See link to nim.py project... 
